# Generated by Django 5.1 on 2024-08-08 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='apellidoMaterno',
            field=models.CharField(blank=True, max_length=70),
        ),
        migrations.AddField(
            model_name='user',
            name='apellidoPaterno',
            field=models.CharField(blank=True, max_length=70),
        ),
        migrations.AddField(
            model_name='user',
            name='nombre',
            field=models.CharField(blank=True, max_length=70),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
