# Generated by Django 5.1 on 2024-08-13 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GestionEscuela', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='materias_alumno',
            old_name='alumno_id',
            new_name='alumno',
        ),
        migrations.RenameField(
            model_name='materias_alumno',
            old_name='materia_id',
            new_name='materia',
        ),
    ]
