# Generated by Django 5.1 on 2024-08-08 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GestionEscuela', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='materias_alumno',
            old_name='materias',
            new_name='idMateria',
        ),
    ]
