# Generated by Django 5.1 on 2024-08-08 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GestionEscuela', '0002_rename_materias_materias_alumno_idmateria'),
    ]

    operations = [
        migrations.RenameField(
            model_name='materias_alumno',
            old_name='idMateria',
            new_name='materias',
        ),
    ]
