# Generated by Django 5.1 on 2024-08-13 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GestionEscuela', '0002_rename_alumno_id_materias_alumno_alumno_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='materias_profesor',
            old_name='materias',
            new_name='materia',
        ),
    ]
